import {
  Quiz,
  QuizQuestion,
  QuizProgress,
  Leaderboard,
  UserStoryProgress,
  Story,
} from '../models/index.js';
import { User } from '../models/index.js';
import { Op } from 'sequelize';
import { logger } from '../utils/logger.js';

/**
 * Save generated quiz with questions to database
 * @param {Object} quizData - Generated quiz object with questions array
 * @param {string} storyId - Optional story ID to associate with quiz
 * @returns {Promise<Object>} Saved quiz with questions
 */
export const saveGeneratedQuiz = async (quizData, storyId = null) => {
  try {
    // Create the quiz
    const quiz = await Quiz.create({
      title: quizData.title || 'Generated Quiz',
      description: quizData.description || '',
      category: quizData.category || 'general',
      difficultyLevel: quizData.difficultyLevel || 'beginner',
      timeLimit: quizData.timeLimit || 10,
      passingScore: quizData.passingScore || 70,
      isPublished: true,
      questionCount: quizData.questions?.length || 0,
      totalPoints: quizData.questions?.reduce((sum, q) => sum + (q.points || 10), 0) || 100,
      tags: ['auto-generated', 'story-quiz'],
      metadata: {
        storyId: storyId || null,
        autoGenerated: true,
        generatedAt: new Date().toISOString(),
      },
    });

    // Create quiz questions
    if (Array.isArray(quizData.questions)) {
      const questions = quizData.questions.map((q, idx) => ({
        quizId: quiz.id,
        sequence: idx,
        type: q.type || 'multiple-choice',
        question: q.question || '',
        options: sanitizeQuizOptions(q.options || []),
        correctAnswer: q.correctAnswer || '',
        points: q.points || 10,
        explanation: q.explanation || '',
        hints: q.hints ? [q.hints] : [],
      }));

      await QuizQuestion.bulkCreate(questions);
      quiz.questionCount = questions.length;
      await quiz.save();
    }

    logger.info(`Generated quiz "${quiz.title}" saved with ID ${quiz.id}`);
    return {
      ...quiz.toJSON(),
      questions: quizData.questions || [],
    };
  } catch (error) {
    logger.error('Error saving generated quiz:', error);
    throw error;
  }
};

/**
 * Sanitize quiz options to remove emoji/symbols
 * @param {Array} options - Array of options
 * @returns {Array} Sanitized options
 */
function sanitizeQuizOptions(options) {
  if (!Array.isArray(options)) return [];
  return options.map((opt) => {
    if (typeof opt !== 'string') return String(opt);
    return opt.replace(/^[\s\uFE0F\u200D\p{Extended_Pictographic}✓✔✗✕☑☒]+/gu, '').trim();
  });
}

/**
 * Generate quiz for a story on-demand (ADMIN/MANUAL)
 * Calls LLM to generate quiz content, saves to DB
 */
export const generateQuizForStoryEndpoint = async (req, res) => {
  try {
    const { storyId, storyData } = req.body;

    if (!storyData || !storyData.title) {
      return res.status(400).json({
        success: false,
        error: 'storyData with title is required',
      });
    }

    logger.info(`Manually triggering quiz generation for story: ${storyData.title}`);

    // Import quiz generator here to avoid circular deps at module load
    const { generateQuizFromStory } = await import('../services/quizGenerator.js');

    const generatedQuiz = await generateQuizFromStory(storyData, storyId);
    const savedQuiz = await saveGeneratedQuiz(generatedQuiz, storyId);

    res.status(201).json({
      success: true,
      message: 'Quiz generated and saved successfully',
      data: savedQuiz,
    });
  } catch (error) {
    logger.error('Error generating quiz for story:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to generate quiz',
      details: error.message,
    });
  }
};

/**
 * Get all quizzes with filtering
 */
export const getAllQuizzes = async (req, res) => {
  try {
    const { category, difficulty, published = true } = req.query;
    
    const where = {};
    if (published === 'true' || published === true) {
      where.isPublished = true;
    }
    if (category) where.category = category;
    if (difficulty) where.difficultyLevel = difficulty;

    const quizzes = await Quiz.findAll({
      where,
      include: [
        {
          model: QuizQuestion,
          as: 'questions',
          attributes: ['id', 'sequence', 'type', 'prompt', 'points'],
        },
      ],
      order: [['createdAt', 'DESC']],
    });

    const playableQuizzes = quizzes.filter(
      (quiz) => Array.isArray(quiz.questions) && quiz.questions.length > 0
    );

    res.json({
      success: true,
      data: playableQuizzes,
      total: playableQuizzes.length,
    });
  } catch (error) {
    console.error('GetAllQuizzes error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch quizzes',
    });
  }
};

/**
 * Get quiz by ID
 */
export const getQuizById = async (req, res) => {
  try {
    const { id } = req.params;

    const quiz = await Quiz.findByPk(id, {
      include: [
        {
          model: QuizQuestion,
          as: 'questions',
          attributes: ['id', 'sequence', 'type', 'prompt', 'options', 'points', 'hints'],
          order: [['sequence', 'ASC']],
        },
      ],
    });

    if (!quiz) {
      return res.status(404).json({
        success: false,
        error: 'Quiz not found',
      });
    }

    res.json({ success: true, data: quiz });
  } catch (error) {
    console.error('GetQuizById error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch quiz',
    });
  }
};

/**
 * Get (or auto-provision) a quiz mapped to a specific story
 */
export const getQuizForStory = async (req, res) => {
  try {
    const { storyId } = req.params;

    const story = await Story.findByPk(storyId);
    if (!story) {
      return res.status(404).json({
        success: false,
        error: 'Story not found',
      });
    }

    const publishedQuizzes = await Quiz.findAll({
      where: { isPublished: true },
      include: [
        {
          model: QuizQuestion,
          as: 'questions',
          attributes: ['id', 'sequence', 'type', 'prompt', 'options', 'points', 'hints'],
        },
      ],
      order: [['createdAt', 'DESC']],
    });

    const hasQuestions = (quiz) => Array.isArray(quiz?.questions) && quiz.questions.length > 0;

    let mappedQuiz = publishedQuizzes.find((quiz) => {
      const mappedStoryId = quiz?.metadata?.storyId || quiz?.metadata?.story_id;
      return mappedStoryId === storyId;
    });

    if (!mappedQuiz) {
      mappedQuiz = publishedQuizzes.find((quiz) => hasQuestions(quiz) && quiz.category === story.category);
    }

    if (!mappedQuiz) {
      mappedQuiz = publishedQuizzes.find((quiz) => hasQuestions(quiz));
    }

    if (!mappedQuiz) {
      const autoQuiz = await Quiz.create({
        title: `${story.title} - Checkpoint Quiz`,
        description: `Quick comprehension quiz for ${story.title}`,
        category: story.category || 'general',
        difficultyLevel: story.difficultyLevel || 'beginner',
        passingScore: 70,
        isPublished: true,
        tags: ['auto-generated', 'story-checkpoint'],
        metadata: {
          storyId,
          autoGenerated: true,
        },
      });

      const generatedQuestions = [
        {
          sequence: 1,
          type: 'multiple-choice',
          prompt: `What is the main lesson from \"${story.title}\"?`,
          options: [
            'Choose safe and respectful actions',
            'Ignore difficult situations',
            'Keep important concerns to yourself',
            'Blame yourself for everything',
          ],
          correctAnswer: 'Choose safe and respectful actions',
          explanation: 'This story is designed to reinforce safe, respectful decision-making.',
          points: 10,
          hints: ['Think about the safest and most positive choice.'],
        },
        {
          sequence: 2,
          type: 'true-false',
          prompt: 'It helps to ask a trusted adult when you are confused or worried.',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: 'Trusted adults can provide support and guidance in difficult moments.',
          points: 10,
          hints: [],
        },
        {
          sequence: 3,
          type: 'multiple-choice',
          prompt: 'What is the best next step after learning from this story?',
          options: [
            'Apply the lesson in real life',
            'Forget it immediately',
            'Avoid talking to anyone',
            'Take unsafe shortcuts',
          ],
          correctAnswer: 'Apply the lesson in real life',
          explanation: 'Learning is most useful when translated into safe daily choices.',
          points: 10,
          hints: ['Choose the answer that reflects practical learning.'],
        },
      ];

      for (const question of generatedQuestions) {
        await QuizQuestion.create({
          quizId: autoQuiz.id,
          ...question,
        });
      }

      autoQuiz.questionCount = generatedQuestions.length;
      autoQuiz.totalPoints = generatedQuestions.reduce((sum, q) => sum + q.points, 0);
      await autoQuiz.save();

      mappedQuiz = await Quiz.findByPk(autoQuiz.id, {
        include: [
          {
            model: QuizQuestion,
            as: 'questions',
            attributes: ['id', 'sequence', 'type', 'prompt', 'options', 'points', 'hints'],
          },
        ],
      });
    }

    return res.json({
      success: true,
      data: mappedQuiz,
    });
  } catch (error) {
    console.error('GetQuizForStory error:', error);
    return res.status(500).json({
      success: false,
      error: 'Failed to fetch story quiz',
    });
  }
};

/**
 * Create new quiz (ADMIN)
 */
export const createQuiz = async (req, res) => {
  try {
    const { title, description, category, difficultyLevel, timeLimit, passingScore, tags } = req.body;

    if (!title || !category) {
      return res.status(400).json({
        success: false,
        error: 'Title and category are required',
      });
    }

    const quiz = await Quiz.create({
      title,
      description,
      category,
      difficultyLevel: difficultyLevel || 'beginner',
      timeLimit,
      passingScore: passingScore || 70,
      tags: tags || [],
    });

    res.status(201).json({
      success: true,
      data: quiz,
    });
  } catch (error) {
    console.error('CreateQuiz error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to create quiz',
    });
  }
};

/**
 * Update quiz (ADMIN)
 */
export const updateQuiz = async (req, res) => {
  try {
    const { id } = req.params;
    const { title, description, category, difficultyLevel, timeLimit, passingScore, isPublished, tags } = req.body;

    const quiz = await Quiz.findByPk(id);

    if (!quiz) {
      return res.status(404).json({
        success: false,
        error: 'Quiz not found',
      });
    }

    if (title) quiz.title = title;
    if (description) quiz.description = description;
    if (category) quiz.category = category;
    if (difficultyLevel) quiz.difficultyLevel = difficultyLevel;
    if (typeof timeLimit !== 'undefined') quiz.timeLimit = timeLimit;
    if (passingScore) quiz.passingScore = passingScore;
    if (typeof isPublished !== 'undefined') quiz.isPublished = isPublished;
    if (tags) quiz.tags = tags;

    await quiz.save();

    res.json({
      success: true,
      data: quiz,
    });
  } catch (error) {
    console.error('UpdateQuiz error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to update quiz',
    });
  }
};

/**
 * Delete quiz (ADMIN)
 */
export const deleteQuiz = async (req, res) => {
  try {
    const { id } = req.params;

    const quiz = await Quiz.findByPk(id);

    if (!quiz) {
      return res.status(404).json({
        success: false,
        error: 'Quiz not found',
      });
    }

    await quiz.destroy();

    res.json({
      success: true,
      message: 'Quiz deleted successfully',
    });
  } catch (error) {
    console.error('DeleteQuiz error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to delete quiz',
    });
  }
};

/**
 * Add question to quiz (ADMIN)
 */
export const addQuestionToQuiz = async (req, res) => {
  try {
    const { id } = req.params;
    const { type, prompt, options, correctAnswer, explanation, points, hints } = req.body;

    const quiz = await Quiz.findByPk(id);

    if (!quiz) {
      return res.status(404).json({
        success: false,
        error: 'Quiz not found',
      });
    }

    // Get next sequence number
    const lastQuestion = await QuizQuestion.findOne({
      where: { quizId: id },
      order: [['sequence', 'DESC']],
    });

    const sequence = (lastQuestion?.sequence || 0) + 1;

    const question = await QuizQuestion.create({
      quizId: id,
      sequence,
      type: type || 'multiple-choice',
      prompt,
      options,
      correctAnswer,
      explanation,
      points: points || 1,
      hints: hints || [],
    });

    // Update quiz counters
    quiz.questionCount = (quiz.questionCount || 0) + 1;
    quiz.totalPoints = (quiz.totalPoints || 0) + (points || 1);
    await quiz.save();

    res.status(201).json({
      success: true,
      data: question,
    });
  } catch (error) {
    console.error('AddQuestionToQuiz error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to add question',
    });
  }
};

/**
 * Update quiz question (ADMIN)
 */
export const updateQuestion = async (req, res) => {
  try {
    const { id, questionId } = req.params;
    const { type, prompt, options, correctAnswer, explanation, points, hints } = req.body;

    const question = await QuizQuestion.findByPk(questionId);

    if (!question || question.quizId !== id) {
      return res.status(404).json({
        success: false,
        error: 'Question not found',
      });
    }

    const pointsDiff = (points || question.points) - question.points;

    if (type) question.type = type;
    if (prompt) question.prompt = prompt;
    if (options) question.options = options;
    if (correctAnswer) question.correctAnswer = correctAnswer;
    if (explanation) question.explanation = explanation;
    if (typeof points !== 'undefined') question.points = points;
    if (hints) question.hints = hints;

    await question.save();

    // Update quiz total points
    if (pointsDiff !== 0) {
      const quiz = await Quiz.findByPk(id);
      quiz.totalPoints = Math.max(0, (quiz.totalPoints || 0) + pointsDiff);
      await quiz.save();
    }

    res.json({
      success: true,
      data: question,
    });
  } catch (error) {
    console.error('UpdateQuestion error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to update question',
    });
  }
};

/**
 * Delete quiz question (ADMIN)
 */
export const deleteQuestion = async (req, res) => {
  try {
    const { id, questionId } = req.params;

    const question = await QuizQuestion.findByPk(questionId);

    if (!question || question.quizId !== id) {
      return res.status(404).json({
        success: false,
        error: 'Question not found',
      });
    }

    const pointsRemoved = question.points;
    await question.destroy();

    // Update quiz counters
    const quiz = await Quiz.findByPk(id);
    quiz.questionCount = Math.max(0, (quiz.questionCount || 0) - 1);
    quiz.totalPoints = Math.max(0, (quiz.totalPoints || 0) - pointsRemoved);
    await quiz.save();

    res.json({
      success: true,
      message: 'Question deleted successfully',
    });
  } catch (error) {
    console.error('DeleteQuestion error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to delete question',
    });
  }
};

/**
 * Submit quiz attempt and calculate score
 */
export const submitQuizAttempt = async (req, res) => {
  try {
    const { quizId } = req.params;
    const { answers = {}, timeSpent, emotionReport } = req.body || {};
    const userId = await resolveQuizUserId(req.user);

    if (!userId) {
      return res.status(401).json({
        success: false,
        error: 'Unauthorized user context',
      });
    }

    const quiz = await Quiz.findByPk(quizId, {
      include: [
        {
          model: QuizQuestion,
          as: 'questions',
          attributes: ['id', 'correctAnswer', 'points', 'sequence'],
        },
      ],
    });

    if (!quiz) {
      return res.status(404).json({
        success: false,
        error: 'Quiz not found',
      });
    }

    if (!Array.isArray(quiz.questions) || quiz.questions.length === 0) {
      return res.status(400).json({
        success: false,
        error: 'Quiz has no questions',
      });
    }

    // Calculate score
    let totalScore = 0;
    let pointsEarned = 0;
    const scoredAnswers = {};

    for (const question of quiz.questions) {
      const userAnswer = answers[question.id];
      const isCorrect = compareAnswers(userAnswer, question.correctAnswer);

      scoredAnswers[question.id] = {
        userAnswer,
        correct: isCorrect,
        points: isCorrect ? question.points : 0,
      };

      pointsEarned += isCorrect ? question.points : 0;
      totalScore += question.points;
    }

    const derivedTotalPoints = quiz.questions.reduce((sum, question) => sum + (question.points || 0), 0);
    const quizTotalPoints = quiz.totalPoints > 0 ? quiz.totalPoints : derivedTotalPoints;

    if (!quizTotalPoints || quizTotalPoints <= 0) {
      return res.status(400).json({
        success: false,
        error: 'Quiz is not configured with valid points',
      });
    }

    const scorePercentage = Math.round((pointsEarned / quizTotalPoints) * 100);
    const passed = scorePercentage >= quiz.passingScore;

    // Store optional assessment emotion report in attempt metadata.
    if (emotionReport && typeof emotionReport === 'object') {
      scoredAnswers.__emotionReport = emotionReport;
    }

    // Create progress record
    const lastAttempt = await QuizProgress.findOne({
      where: { userId, quizId },
      order: [['attempt', 'DESC']],
    });

    const attempt = (lastAttempt?.attempt || 0) + 1;

    const progress = await QuizProgress.create({
      userId,
      quizId,
      attempt,
      score: scorePercentage,
      pointsEarned,
      totalPoints: quizTotalPoints,
      passed,
      timeSpent,
      answers: scoredAnswers,
      completedAt: new Date(),
    });

    // Update quiz stats
    const allAttempts = await QuizProgress.findAll({
      where: { quizId },
    });

    const totalAttempts = allAttempts.length;
    const avgScore = Math.round(
      allAttempts.reduce((sum, a) => sum + a.score, 0) / totalAttempts
    );

    quiz.attemptCount = totalAttempts;
    quiz.averageScore = avgScore;
    quiz.totalPoints = quizTotalPoints;
    await quiz.save();

    await syncLeaderboardForUser(userId);

    res.json({
      success: true,
      data: {
        progress,
        scorePercentage,
        passed,
        pointsEarned,
        totalPoints: quizTotalPoints,
        attempt,
        emotionReport: scoredAnswers.__emotionReport || null,
      },
    });
  } catch (error) {
    console.error('SubmitQuizAttempt error:', error);
    res.status(500).json({
      success: false,
      error: error?.message || 'Failed to submit quiz',
    });
  }
};

/**
 * Get user's quiz attempts
 */
export const getUserQuizAttempts = async (req, res) => {
  try {
    const { quizId } = req.params;
    const userId = await resolveQuizUserId(req.user);

    if (!userId) {
      return res.status(401).json({
        success: false,
        error: 'Unauthorized user context',
      });
    }

    const attempts = await QuizProgress.findAll({
      where: { userId, quizId },
      order: [['attempt', 'DESC']],
    });

    res.json({
      success: true,
      data: attempts,
    });
  } catch (error) {
    console.error('GetUserQuizAttempts error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch quiz attempts',
    });
  }
};

/**
 * Get user's quiz statistics
 */
export const getUserQuizStats = async (req, res) => {
  try {
    const userId = await resolveQuizUserId(req.user);

    if (!userId) {
      return res.status(401).json({
        success: false,
        error: 'Unauthorized user context',
      });
    }

    const stats = await QuizProgress.findAll({
      where: { userId },
      include: [
        {
          model: Quiz,
          as: 'quiz',
          attributes: ['id', 'title', 'category', 'difficultyLevel'],
        },
      ],
      order: [['completedAt', 'DESC']],
    });

    const quizzesCompleted = new Set(stats.map(s => s.quizId)).size;
    const totalPoints = stats.reduce((sum, s) => sum + s.pointsEarned, 0);
    const avgScore = stats.length > 0
      ? Math.round(stats.reduce((sum, s) => sum + s.score, 0) / stats.length)
      : 0;
    const passCount = stats.filter(s => s.passed).length;

    res.json({
      success: true,
      data: {
        totalAttempts: stats.length,
        quizzesCompleted,
        totalPoints,
        avgScore,
        passCount,
        attempts: stats,
      },
    });
  } catch (error) {
    console.error('GetUserQuizStats error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch quiz statistics',
    });
  }
};

/**
 * Helper function to compare user answer with correct answer
 */
function compareAnswers(userAnswer, correctAnswer) {
  if (!userAnswer || !correctAnswer) return false;

  // For multiple choice / true false
  if (typeof correctAnswer === 'string' || typeof correctAnswer === 'boolean') {
    return userAnswer === correctAnswer;
  }

  // For arrays (multiple answers)
  if (Array.isArray(correctAnswer)) {
    if (!Array.isArray(userAnswer)) return false;
    if (userAnswer.length !== correctAnswer.length) return false;
    return userAnswer.sort().every((a, i) => a === correctAnswer.sort()[i]);
  }

  // For objects (matching, complex answers)
  if (typeof correctAnswer === 'object') {
    return JSON.stringify(userAnswer) === JSON.stringify(correctAnswer);
  }

  return false;
}

function isUuid(value) {
  return typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}

async function resolveQuizUserId(authUser) {
  const authId = authUser?.id;
  const authEmail = authUser?.email;

  if (!authId && !authEmail) {
    return null;
  }

  if (authId && isUuid(authId)) {
    const byId = await User.findByPk(authId, { paranoid: false });
    if (byId) {
      return byId.id;
    }
  }

  if (authEmail) {
    const byEmail = await User.findOne({
      where: { email: String(authEmail).toLowerCase() },
      paranoid: false,
    });

    if (byEmail) {
      return byEmail.id;
    }

    const created = await User.create({
      ...(authId && isUuid(authId) ? { id: authId } : {}),
      email: String(authEmail).toLowerCase(),
      firstName: 'Learner',
      oauthProvider: 'local',
    });

    return created.id;
  }

  return null;
}

function getPeriodStart(period) {
  if (period === 'weekly') {
    return new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  }

  if (period === 'monthly') {
    return new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  }

  return new Date('2000-01-01');
}

async function syncLeaderboardForUser(userId) {
  const periods = ['all-time', 'monthly', 'weekly'];

  for (const period of periods) {
    const startDate = getPeriodStart(period);

    const [quizzes, stories] = await Promise.all([
      QuizProgress.findAll({
        where: {
          userId,
          completedAt: { [Op.gte]: startDate },
        },
      }),
      UserStoryProgress.findAll({
        where: {
          userId,
          status: 'completed',
          completedAt: { [Op.gte]: startDate },
        },
      }),
    ]);

    const totalQuizPoints = quizzes.reduce((sum, item) => sum + (item.pointsEarned || 0), 0);
    const totalStoryPoints = stories.reduce((sum, item) => sum + (item.pointsEarned || 0), 0);
    const totalPoints = totalQuizPoints + totalStoryPoints;

    const quizzesCompleted = new Set(quizzes.map((item) => item.quizId)).size;
    const storiesCompleted = stories.length;

    const [entry] = await Leaderboard.findOrCreate({
      where: { userId, period },
      defaults: {
        userId,
        period,
        rank: 0,
        totalPoints,
        quizzesCompleted,
        storiesCompleted,
        journalCount: 0,
        moodLogsCount: 0,
        streak: 0,
        lastActivityAt: new Date(),
        periodStartAt: startDate,
      },
    });

    if (entry) {
      await entry.update({
        totalPoints,
        quizzesCompleted,
        storiesCompleted,
        moodLogsCount: 0,
        lastActivityAt: new Date(),
        periodStartAt: startDate,
      });
    }

    const ordered = await Leaderboard.findAll({
      where: { period },
      order: [
        ['totalPoints', 'DESC'],
        ['lastActivityAt', 'ASC'],
      ],
    });

    await Promise.all(
      ordered.map((row, index) => row.update({ rank: index + 1 }))
    );
  }
}

export default {
  getAllQuizzes,
  getQuizById,
  createQuiz,
  updateQuiz,
  deleteQuiz,
  addQuestionToQuiz,
  updateQuestion,
  deleteQuestion,
  getQuizForStory,
  submitQuizAttempt,
  getUserQuizAttempts,
  getUserQuizStats,
};
